service: parsa-api
frameworkVersion: "3.32.2"

provider:
  name: aws
  architecture: arm64
  runtime: nodejs18.x
  stage: local

plugins:
  - serverless-offline

functions:
  function1:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get

custom:
  serverless-offline:
    lambdaPort: 3002
    httpPort: 3003
