name: deploy
run-name: ${{github.actor}} is learning Github Actions
on: [push]
jobs:
  after-check-bats-version:
    needs: check-bats-version
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3 #parsa see if i can swap order
        with:
          node-version: "18.17.0"
      - run: npm install -g bats
      - run: bats -v
      - run: ls
  check-bats-version:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.17.0"
      - run: npm install -g bats
      - run: bats -v
